apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.test.triggered
      requests:
        - curl --request POST
          http://jenkins.35.184.57.17.nip.io/job/Keptn%20test%20finished%20pipeline/buildWithParameters?token={{.env.secret_keptnjenkinsnewtoken_token}}&shkeptncontext={{.shkeptncontext}}&triggeredid={{.id}}&Project={{.data.project}}&Service={{.data.service}}&Stage={{.data.stage}}
      envFrom:
        - name: secret_keptnjenkinsnewtoken_token
          secretRef:
            name: keptn-jenkins-new-token
            key: token
      subscriptionID: a96eff2a-763b-4521-ae04-9526c47904fc
